spring:
  application:
    name: timeslot-telegram-bot
  datasource:
    url: "jdbc:postgresql://db:5432/postgres"
    username: timeslot
    password: timeslot
    hikari:
      maximum-pool-size: 10
bot:
  bot-name: TimeslotZernoBot
  bot-token: 7008151001:AAEVyDtVJ13EG_jA6ArvsIQ7TEV2Ujda-7Q
client:
  timeslot-parser:
    url: "http://timeslot-parser:8082"
server:
  port: 8083